server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
  connectionTimeout: 180000
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.hengyangshiyuan.hrsystem.bean   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                      
    
spring:
   application:
    name: hrsystem-manager
   datasource:
   ## type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://localhost:3306/book           
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                         
      max-wait-millis: 200                                  
   mvc:
    view:
      prefix: /pages/
      suffix: .jsp
   http:
    multipart:
      max-file-size: 50mb
      max-request-size: 50mb